### ISSUE TITLE
Annotation file 出力時にdict key errorになる事がある

### ISSUE THREAD

**Issue by citrusjunos** [matbrain/deepscholar-nlp#1]
- gen_anno.py 実行時に"gen_anno.py", line 107 (prop = prop_dict[property_id]['name']) で KeyError: 'pYKgf7n9HEleJ9mhghYZ') となりました。そこで以下のError handlingを行うことで暫定的に回避し、一連のannotation file出力は成功しました。
line 104を以下の様に修正
```
# if 'parentId' in node and 'propertyId' in node: 
if 'parentId' in node and 'propertyId' in node and prop_dict.get(node['propertyId']) is not None:
```

**Comment by hshindo** [comment]
fixed
